### ISSUE TITLE
support displaying new mention nip

### ISSUE THREAD

**Issue by digi-monkey** [digi-monkey/flycat-web#103]
- https://github.com/nostr-protocol/nips/blob/master/27.md

we should keep the nip-08 mention rendering, while support nip-27 mentioning. eventually we will remove the nip-08

**Comment by digi-monkey** [comment]
please note this issue is only for rendering. to allow users input mention on their short notes, go to https://github.com/digi-monkey/flycat-web/issues/49

**Comment by Heqingsong** [comment]
This function has been implemented https://github.com/digi-monkey/flycat-web/pull/115
