### ISSUE TITLE
flycat的功能用不了

### ISSUE THREAD

**Issue by Hoodrh** [digi-monkey/flycat-web#21]
您好，我使用了flycat的网页端，登录是可以的，但是登录后只能查看消息，功能性操作都不能使用，希望可以修复。
1. 关注他人功能不能用，
2. 创建博客功能不能用
3. 首页发帖功能也不能用；

**Comment by digi-monkey** [comment]
> 您好，我使用了flycat的网页端，登录是可以的，但是登录后只能查看消息，功能性操作都不能使用，希望可以修复。
> 
>     1. 关注他人功能不能用，
> 
>     2. 创建博客功能不能用
> 
>     3. 首页发帖功能也不能用；

这三个功能都需要用到私钥，你登陆的时候有填私钥吗？另外有没有错误提示

**Comment by digi-monkey** [comment]
@Hoodrh 最近支持了 nip07，可以用 nos2x 或者 闪电网络钱包插件 alby 登陆，你也可以用这种方式更安全。

**Comment by digi-monkey** [comment]
closing since no activites. feel free to re-open it if you got any problems

**Comment by Hoodrh** [comment]
> > 您好，我使用了flycat的网页端，登录是可以的，但是登录后只能查看消息，功能性操作都不能使用，希望可以修复。
> > ```
> > 1. 关注他人功能不能用，
> > 
> > 2. 创建博客功能不能用
> > 
> > 3. 首页发帖功能也不能用；
> > ```
> 
> @Hoodrh 这三个功能都需要用到私钥，你登陆的时候有填私钥吗？另外有没有错误提示

我是在已经用扩展器授权登录情况下的，点击无效，也没有错误提示。（最近没用，不知道您们是否有更新

**Comment by digi-monkey** [comment]
有的，你是使用nostr2x还是 alby? 可以提供下截图、浏览器型号、电脑系统等信息，方便我们这边排查下吗
