### ISSUE TITLE
The html a tag is automatically modified with the attribute

### ISSUE THREAD

**Issue by quake** [digi-monkey/flycat-web#266]
Publish an note:
```text
test link: <a href="#">test</a>
```

got:
```text
test link: <a href="#" target="_blank" rel="noopener">test</a>
```

<img width="618" alt="image" src="https://github.com/digi-monkey/flycat-web/assets/8990/79b10036-056c-42d5-abf9-40203a163be7">

**Comment by digi-monkey** [comment]
resolved in

- https://github.com/digi-monkey/flycat-web/pull/348
