### ISSUE TITLE
Overridden background color

### ISSUE THREAD

**Issue by ShookLyngs** [digi-monkey/flycat-web#307]
In certain pages, the `background-color` of the `<body>` is overridden.

Take the [home page](https://flycat.club/) as an example:

![image](https://github.com/digi-monkey/flycat-web/assets/44739165/38c5a674-c7c7-46d5-8f7e-6eba14163fe6)

You can observe that the current `background-color` of the `<body>` is set to `--adm-color-background`, while the correct one should be `--neutral-01`, which has been overridden. This issue is caused by the global style of `antd-mobile`.

To resolve it, you can add the following CSS to your styles:

```css
:root:root {
  --adm-color-background: var(--neutral-01);
}
```

This solution is suggested in the [Ant Design Mobile theming guide](https://mobile.ant.design/guide/theming#theming).

**Comment by digi-monkey** [comment]
thx! would you mind submitting a PR to fix this? or I will submit one later if i got a minute
