### ISSUE TITLE
Replace sidebar buttons with links

### ISSUE THREAD

**Issue by ShookLyngs** [digi-monkey/flycat-web#311]
This is the sidebar of flycat:

![image](https://github.com/digi-monkey/flycat-web/assets/44739165/91bae98f-36de-413a-9245-e0d44b62c226)

Currently, the sidebar of flycat is just a simple list of `<li>`. 
I suggest replacing them with links (`<Link>` or `<a>`) for the following reasons:

- Improved readability: When you hover your mouse over a link, you can see the destination it will take you to.
- Enhanced accessibility: By holding Ctrl (or Command on macOS) and clicking a link, you can open it in a new tab.

Overall, I think using links instead of buttons can make users feel more comfortable and secure because links can provide a more expected outcome for users. Thanks!

**Comment by RongxinZhang** [comment]
@ShookLyngs @digi-monkey point me to the file, and I can make the change.
