### ISSUE TITLE
Feature request: Show a button to show new notes

### ISSUE THREAD

**Issue by bitcoinuser** [digi-monkey/flycat-web#32]
Hi,

Feature request: Show a button to show new notes.

**Comment by digi-monkey** [comment]
yeah this should be implemented for basic function

**Comment by digi-monkey** [comment]
- https://github.com/digi-monkey/flycat-web/pull/113

sorry for the late response @bitcoinuser the load more button has been merged. feel free to reopen this issue if you have more questions.
