### ISSUE TITLE
sometimes relay-selector UI truncated

### ISSUE THREAD

**Issue by digi-monkey** [digi-monkey/flycat-web#396]
<img width="712" alt="image" src="https://github.com/digi-monkey/flycat-web/assets/105776364/59a4652c-6a77-4d08-89cb-58c8ef5992a5">

the relay-selector should be 100% width, sometime it is shorted maybe some css bugs

**Comment by ahonn** [comment]
It seems that RelaySelector is using antd. I would like to refactor this component to improve its UX/UI. What do you think?

**Comment by digi-monkey** [comment]
> It seems that RelaySelector is using antd. I would like to refactor this component to improve its UX/UI. What do you think?

cool, I think it is good idea since the antd is not very ideal to this component's design here

**Comment by digi-monkey** [comment]
@ahonn  do you want to refactor this item this week? Shall I move this task into our `v0.2.8` plan?

**Comment by ahonn** [comment]
> @ahonn do you want to refactor this item this week? Shall I move this task into our `v0.2.8` plan?

Yes, I plan to refactor this this week.

**Comment by digi-monkey** [comment]
- https://github.com/digi-monkey/flycat-web/pull/408
