### ISSUE TITLE
note clicking image popup not working well

### ISSUE THREAD

**Issue by digi-monkey** [digi-monkey/flycat-web#67]
## on mobile
![image](https://user-images.githubusercontent.com/105776364/227458349-8d356f45-521b-4e84-89c3-021cd8e95b97.png)
## desktop
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/105776364/227458394-52c72f97-2b65-4d15-b355-08961a361327.png">

**Comment by Heqingsong** [comment]
The issue has been fixed.
