### ISSUE TITLE
some articles can't be opened

### ISSUE THREAD

**Issue by digi-monkey** [digi-monkey/flycat-web#68]
- https://flycat.club/user/28246aeedb67ca7b2501cb6580dc02cb12b02caaced1f729bb6195d062b108ad 's article (seems url went wrong but it can be opened from habla https://habla.news/a/naddr1qpsksar5wpen5te0w3n8gcewd9hj7arxw33j6ur0v33kzum59u6rqdedvdskuttzd96xxmmfdckhyetpvd5z6vfdxqcrqtfsxqcz6cne94482mn995cn2arg94mkjarg94kkzar5dpjhwttdv4axjmnndd5hxtczyq5zg6hwmdnu57e9q89ktqxuqt939vpv4t8draefhdset5rzkyy26qcyqqq823c7jymst

**Comment by Heqingsong** [comment]
The issue has been fixed https://github.com/digi-monkey/flycat-web/pull/81
