### ISSUE TITLE
login page css not really working

### ISSUE THREAD

**Issue by digi-monkey** [digi-monkey/flycat-web#91]
it supposed to look like this(and it did under `yarn dev`)

![image](https://user-images.githubusercontent.com/105776364/230126937-e5a2dd26-ff3c-46f5-ae3d-fc3e354467c7.png)

but instead it looks like this(under `yarn start`)

<img width="659" alt="image" src="https://user-images.githubusercontent.com/105776364/230127125-06209f94-cf4f-4619-83b6-b3ba24f6b5a2.png">

**Comment by Heqingsong** [comment]
The issue has been fixed https://github.com/digi-monkey/flycat-web/pull/93
